/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeSortableListRouteImport } from './routes/prototype.sortable-list'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedTeamsRouteRouteImport } from './routes/_authenticated/teams/route'
import { Route as AuthenticatedPlayersRouteRouteImport } from './routes/_authenticated/players/route'
import { Route as AuthenticatedGamesRouteRouteImport } from './routes/_authenticated/games/route'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedTeamsNewRouteImport } from './routes/_authenticated/teams/new'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedPlayersMeRouteImport } from './routes/_authenticated/players/me'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players/$playerId'
import { Route as AuthenticatedGamesNewRouteImport } from './routes/_authenticated/games/new'
import { Route as AuthenticatedGamesGameIdRouteImport } from './routes/_authenticated/games/$gameId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSortableListRoute = PrototypeSortableListRouteImport.update({
  id: '/prototype/sortable-list',
  path: '/prototype/sortable-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsRouteRoute = AuthenticatedTeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayersRouteRoute =
  AuthenticatedPlayersRouteRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesRouteRoute = AuthenticatedGamesRouteRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamsRouteRoute,
} as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlayersRouteRoute,
  } as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGamesRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsNewRoute = AuthenticatedTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTeamsRouteRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRouteRoute,
  } as any)
const AuthenticatedPlayersMeRoute = AuthenticatedPlayersMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedPlayersRouteRoute,
} as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => AuthenticatedPlayersRouteRoute,
  } as any)
const AuthenticatedGamesNewRoute = AuthenticatedGamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGamesRouteRoute,
} as any)
const AuthenticatedGamesGameIdRoute =
  AuthenticatedGamesGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => AuthenticatedGamesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof AuthenticatedGamesRouteRouteWithChildren
  '/players': typeof AuthenticatedPlayersRouteRouteWithChildren
  '/teams': typeof AuthenticatedTeamsRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/prototype/sortable-list': typeof PrototypeSortableListRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/players/me': typeof AuthenticatedPlayersMeRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/prototype/sortable-list': typeof PrototypeSortableListRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/players/me': typeof AuthenticatedPlayersMeRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/games': typeof AuthenticatedGamesRouteRouteWithChildren
  '/_authenticated/players': typeof AuthenticatedPlayersRouteRouteWithChildren
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/prototype/sortable-list': typeof PrototypeSortableListRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/_authenticated/games/new': typeof AuthenticatedGamesNewRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/players/me': typeof AuthenticatedPlayersMeRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/teams/new': typeof AuthenticatedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/players'
    | '/teams'
    | '/app'
    | '/prototype/sortable-list'
    | '/games/$gameId'
    | '/games/new'
    | '/players/$playerId'
    | '/players/me'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/games/'
    | '/players/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/prototype/sortable-list'
    | '/games/$gameId'
    | '/games/new'
    | '/players/$playerId'
    | '/players/me'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/games'
    | '/players'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/games'
    | '/_authenticated/players'
    | '/_authenticated/teams'
    | '/_authenticated/app'
    | '/prototype/sortable-list'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/games/new'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/players/me'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/new'
    | '/api/auth/$'
    | '/_authenticated/games/'
    | '/_authenticated/players/'
    | '/_authenticated/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrototypeSortableListRoute: typeof PrototypeSortableListRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/sortable-list': {
      id: '/prototype/sortable-list'
      path: '/prototype/sortable-list'
      fullPath: '/prototype/sortable-list'
      preLoaderRoute: typeof PrototypeSortableListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsRouteRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedPlayersRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedGamesRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/new': {
      id: '/_authenticated/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AuthenticatedTeamsNewRouteImport
      parentRoute: typeof AuthenticatedTeamsRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRouteRoute
    }
    '/_authenticated/players/me': {
      id: '/_authenticated/players/me'
      path: '/me'
      fullPath: '/players/me'
      preLoaderRoute: typeof AuthenticatedPlayersMeRouteImport
      parentRoute: typeof AuthenticatedPlayersRouteRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedPlayersRouteRoute
    }
    '/_authenticated/games/new': {
      id: '/_authenticated/games/new'
      path: '/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof AuthenticatedGamesNewRouteImport
      parentRoute: typeof AuthenticatedGamesRouteRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedGamesRouteRoute
    }
  }
}

interface AuthenticatedGamesRouteRouteChildren {
  AuthenticatedGamesGameIdRoute: typeof AuthenticatedGamesGameIdRoute
  AuthenticatedGamesNewRoute: typeof AuthenticatedGamesNewRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
}

const AuthenticatedGamesRouteRouteChildren: AuthenticatedGamesRouteRouteChildren =
  {
    AuthenticatedGamesGameIdRoute: AuthenticatedGamesGameIdRoute,
    AuthenticatedGamesNewRoute: AuthenticatedGamesNewRoute,
    AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  }

const AuthenticatedGamesRouteRouteWithChildren =
  AuthenticatedGamesRouteRoute._addFileChildren(
    AuthenticatedGamesRouteRouteChildren,
  )

interface AuthenticatedPlayersRouteRouteChildren {
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedPlayersMeRoute: typeof AuthenticatedPlayersMeRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
}

const AuthenticatedPlayersRouteRouteChildren: AuthenticatedPlayersRouteRouteChildren =
  {
    AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
    AuthenticatedPlayersMeRoute: AuthenticatedPlayersMeRoute,
    AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  }

const AuthenticatedPlayersRouteRouteWithChildren =
  AuthenticatedPlayersRouteRoute._addFileChildren(
    AuthenticatedPlayersRouteRouteChildren,
  )

interface AuthenticatedTeamsRouteRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedTeamsNewRoute: typeof AuthenticatedTeamsNewRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedTeamsRouteRouteChildren: AuthenticatedTeamsRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
    AuthenticatedTeamsNewRoute: AuthenticatedTeamsNewRoute,
    AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  }

const AuthenticatedTeamsRouteRouteWithChildren =
  AuthenticatedTeamsRouteRoute._addFileChildren(
    AuthenticatedTeamsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGamesRouteRoute: typeof AuthenticatedGamesRouteRouteWithChildren
  AuthenticatedPlayersRouteRoute: typeof AuthenticatedPlayersRouteRouteWithChildren
  AuthenticatedTeamsRouteRoute: typeof AuthenticatedTeamsRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGamesRouteRoute: AuthenticatedGamesRouteRouteWithChildren,
  AuthenticatedPlayersRouteRoute: AuthenticatedPlayersRouteRouteWithChildren,
  AuthenticatedTeamsRouteRoute: AuthenticatedTeamsRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrototypeSortableListRoute: PrototypeSortableListRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
